import React from 'react'
import { AllRaces } from '../Components/Races/AllRaces'

export const Home = () => {
  
  return (
    <>
    <AllRaces/>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    </>
  )
}
