import React from 'react'
import PositionsLastRece from '../Components/Races/PositionsLastRece'
import { Drivers } from '../Components/Drivers/Drivers'

export const Home = () => {
  
  return (
    <>
    <Drivers/>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    <div>Home</div>
    </>
  )
}
